name=Soldered LSM9DS1TR Arduino Library
version=1.0.0
author=Soldered
maintainer=Soldered <soldered@soldered.com>
sentence=Library for the LSM9DS1TR breakout board by Soldered.
paragraph=This mini but mighty module bundles together a 3D accelerometer, a 3D gyroscope, and a 3D magnetometer. It lets you monitor not only linear and rotational movements but also the magnetic field surrounding your projects. Despite its pocket-size, it offers high-accuracy measurements — ±16 g for the accelerometer, ±2000 dps for the gyroscope, and ±16 Gauss for the magnetometer.
category=Sensors
url=https://solde.red/333069
repository=https://github.com/SolderedElectronics/Soldered-LSM9DS1TR-Arduino-Library
architectures=*
includes=LSM9DS1TR-SOLDERED.h
